import numpy as np
arr = np.zeros(10)
print(arr)
arr = np.ones(10)
print(arr)
arr = np.linspace(5,5,10)
print(arr)
arr = np.arange(10,51)
print(arr)
arr = np.arange(10,51,2)
print(arr)
arr = np.arange(0,9).reshape((3,3))
print(arr)
arr = np.eye(3)
print(arr)
arr = np.random.rand(1)
print(arr)
arr = np.random.randn(25)
print(arr)
arr = np.linspace(0,1,101)/100
print(arr)
arr = np.linspace(0,1,20)
print(arr)
arr = np.arange(1,26).reshape(5,5)
print(arr)
print(arr[2:5, 1:5])
print(arr[0:3,1].reshape(3,1))
print(arr[4])
print(arr[3:5])
print(arr.sum())
print(np.std(arr))
#Soma as colunas
print(arr.sum(axis = 0))
#Soma as linhas
print(arr.sum(axis = 1))
